name: onion work
on:
  issues:
    types: labeled
jobs:

 StartWorks:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          echo "startWorks this git clone"
          pwd
          ls
      - id: setCountRun
        run: echo "[1,2,3,4,5]"
    outputs:
       matrix: ${{ steps.setCountRun.outputs.matrix }}
 ManyWorks:
    runs-on: ubuntu-latest
    needs: StartWorks
    strategy:
      matrix:
        job: ${{ fromJSON(needs.StartWorks.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v1
      - name: start $JOB
        if: contains(github.event.label.name, 'bug')
        run: |
          echo $JOB
        env:
          NUM_JOBS: 5
          JOB: ${{ matrix.job }}
 EndWorks:
    runs-on: ubuntu-latest
    if: always()
    needs: ManyWorks
    steps:
      - name: check
        run: |
          echo "endWorks this push"
          pwd
          ls
      - name: start time
        run: |
          date
