name: onion work
on:
  issues:
    types: labeled
jobs:
 StartWorks:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
 StartWorks1:
    runs-on: ubuntu-latest
    needs: StartWorks
    steps:
    - id: step1
      run: echo ${{needs.StartWorks.outputs.output1}}
 ManyWorks:
    runs-on: ubuntu-latest
    needs: StartWorks
    strategy:
      matrix:
        job: ${{needs.StartWorks.outputs.output1}}
    steps:
      - uses: actions/checkout@v1
      - name: start $JOB
        run: |
          echo $JOB
        env:
          NUM_JOBS: 5
          JOB: ${{ matrix.job }}
 EndWorks:
    runs-on: ubuntu-latest
    if: always()
    needs: ManyWorks
    steps:
      - name: check
        run: |
          echo "endWorks this push"
          pwd
          ls
      - name: start time
        run: |
          date
