name: onion work
on:
  issues:
    types: labeled
jobs:
 StartWorks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:  
    - uses: actions/checkout@v2
      with:
       repository: ihsinme/OnionBase
       token: ${{ secrets.ACCESS_TOKEN }}
       ref: devTools
       path: devTools
    - name: tmp works del after dbg
      run: |
       ls ./ -al
       echo "123"
       ls devTools/
    - id: list_dirs
      run: echo "::set-output name=matrix::$(ls devTools/workModuleRun/*.py|jq -cnR '[inputs | select(length>0)]')"
 ManyWorks:
    runs-on: ubuntu-latest
    needs: StartWorks
    strategy:
      matrix:
        job: ${{fromJson(needs.StartWorks.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v1
      - name: start $JOB
        run: |
          echo $JOB
        env:
          JOB: ${{ matrix.job }}
 EndWorks:
    runs-on: ubuntu-latest
#    if: always()
    needs: ManyWorks
    steps:
      - name: check
        run: |
          echo "endWorks this push"
          pwd
          ls
      - name: start time
        run: |
          date
