name: onion work
on:
  schedule:
    - cron:  '0 */8 * * *'
jobs:
 StartWorks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:  
    - uses: actions/checkout@v3
      with:
       repository: ihsinme/OnionBase
       token: ${{ secrets.ACCESS_TOKEN }}
       ref: devTools
       path: devTools
    - id: list_dirs
      run: echo "::set-output name=matrix::$(ls devTools/workModuleRun/*.py|jq -cnR '[inputs | select(length>0)]')"
 StartWorksWin:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:  
    - uses: actions/checkout@v3
      with:
       repository: ihsinme/OnionBase
       token: ${{ secrets.ACCESS_TOKEN }}
       ref: devTools
       path: devTools
    - id: list_dirs
      run: echo "::set-output name=matrix::$(ls devTools/workModuleRun/onlyWin/*.py|jq -cnR '[inputs | select(length>0)]')"   
 ManyWorks:
    runs-on: ubuntu-latest
    needs: StartWorks
    strategy:
      fail-fast: false
      matrix:
        job: ${{fromJson(needs.StartWorks.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v3
      with:
       repository: ihsinme/OnionBase
       token: ${{ secrets.ACCESS_TOKEN }}
       ref: devTools
       path: devTools
    - name: Free disk space
      run: |
        sudo df -h 
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt-get clean
        sudo apt-get autoremove -y
        sudo apt-get autoclean -y
        sudo rm -rf /usr/local/lib/android
        docker rmi $(docker image ls -aq)        
        sudo df -h 
    - name: start $JOB
      run: |
          sudo python3 $JOB
      env:
        JOB: ${{ matrix.job }}
 ManyWorksWin:
    runs-on: windows-latest
    needs: StartWorksWin
    strategy:
      fail-fast: false
      matrix:
        job: ${{fromJson(needs.StartWorksWin.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v3
      with:
       repository: ihsinme/OnionBase
       token: ${{ secrets.ACCESS_TOKEN }}
       ref: devTools
       path: devTools
    - name: start ${{ matrix.job }}
      run: python ${{ matrix.job }}
 EndWorks:
    runs-on: ubuntu-latest
#    if: always()
    needs: [ManyWorks, ManyWorksWin] 
    steps:
      - name: check
        run: |
          echo "endWorks this push"
          pwd
          ls
      - name: start time
        run: |
          date
