name: test onion work
on:
  issue_comment:
    types: [created]
jobs:
 StartWorks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:  
    - uses: actions/checkout@v2
      with:
       repository: ihsinme/OnionBase
       token: ${{ secrets.ACCESS_TOKEN }}
       ref: devTools
       path: devTools
    - id: list_dirs
      run: echo "::set-output name=matrix::$(ls devTools/workModuleTest/*.py|jq -cnR '[inputs | select(length>0)]')"
 StartWorksWin:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrixWin}}
    steps:  
    - uses: actions/checkout@v2
      with:
       repository: ihsinme/OnionBase
       token: ${{ secrets.ACCESS_TOKEN }}
       ref: devTools
       path: devTools
    - id: list_dirs_windows
      run: echo "::set-output name=matrixWin::$(ls devTools/workModuleTest/onlyWin/*.py|jq -cnR '[inputs | select(length>0)]')"      

 ManyWorks:
    runs-on: ubuntu-latest
    needs: StartWorks
    strategy:
      fail-fast: false
      matrix:
        job: ${{fromJson(needs.StartWorks.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v2
      with:
       repository: ihsinme/OnionBase
       token: ${{ secrets.ACCESS_TOKEN }}
       ref: devTools
       path: devTools
    - name: start $JOB
      run: |
          sudo python3 $JOB
      env:
        JOB: ${{ matrix.job }}
 ManyWorksWin:
    runs-on: windows-latest
    needs: StartWorksWin
    strategy:
      fail-fast: false
      matrix:
        job: ${{fromJson(needs.StartWorksWin.outputs.matrixWin)}}
    steps:
    - uses: actions/checkout@v2
      with:
       repository: ihsinme/OnionBase
       token: ${{ secrets.ACCESS_TOKEN }}
       ref: devTools
       path: devTools
    - name: start $JOB
      run: |
          sudo python3 $JOB
      env:
        JOB: ${{ matrix.job }}

 EndWorks:
    runs-on: ubuntu-latest
#    if: always()
    needs: ManyWorks
    steps:
      - name: check
        run: |
          echo "endWorks this push"
          pwd
          ls
      - name: start time
        run: |
          date
